nginx_domain: example.com

nginx_enable_tls: true

nginx_access_log: /var/log/nginx/access.log
nginx_error_log: /var/log/nginx/error.log

proxy_connect_timeout: 60s
proxy_send_timeout: 60s
proxy_read_timeout: 60s
proxy_port: 3000